proje1/proje1/Controllers/PartialController.cs
using proje1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proje1.Controllers
{
    public class PartialController : Controller
    {
        // GET: Partial
        public PartialViewResult BildirimMenusu()
        {
            return PartialView(new Bildirim().SiparisBekleyenListe());
        }
    }
}

proje1/proje1/Views/Shared/Arama.cshtml
@using (@Html.BeginForm("Ara", "Home", FormMethod.Get, new { @class = "form-inline navbar-search" }))

{
    <input id="" name="b" class="srchTxt" type="text" placeholder="Arama" />

    <button type="submit" id="submitButton" class="btn btn-primary">Ara</button>
}

proje1/proje1/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | DataTables</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/AdminLTE/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="/AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/AdminLTE/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="/AdminLTE/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/AdminLTE/dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
         

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>

                <!-- Messages Dropdown Menu -->
                
                <!-- Notifications Dropdown Menu -->
                @Html.Action("BildirimMenusu","Partial")
               
                
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/AdminLTE/index3.html" class="brand-link">
                <img src="/AdminLTE/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                

                <!-- SidebarSearch Form -->
                

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->


                        <li class="nav-item">
                            <a href="/Home/Index" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Web Sayfası
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="/AdminHome/Index" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Anasayfa
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                        </li>





                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Kategori
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="/Kategori/Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Kategori Ekle</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/Kategori/index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Kategori İşlemleri</p>
                                    </a>
                                </li>

                            </ul>
                        </li>


                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Ürün
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="/Urun/Create" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Urun Ekle</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/Urun/index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Ürün İşlemleri</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Siparişler
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li> <a href="/Order/Index"><i class="far fa-circle nav-icon"></i>Tüm Siparişler</a></li>
                                <li> <a href="/Order/BeklenenSiparisler"><i class="far fa-circle nav-icon"></i>Bekleyen Siparişler</a></li>
                                <li> <a href="/Order/TamamlananSiparisler"><i class="far fa-circle nav-icon"></i>Tamamlanan Siparişler</a></li>
                                <li> <a href="/Order/PaketlenenSiparisler"><i class="far fa-circle nav-icon"></i>Paketlenen Siparişler</a></li>
                                <li> <a href="/Order/KargolananSiparisler"><i class="far fa-circle nav-icon"></i>Kargolanan Siparişler</a></li>
                            </ul>
                        </li>












                    </ul>
                </nav>
                <!-- /.sidebar-menu -->




            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        
                        
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.1.0
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="/AdminLTE/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="/AdminLTE/plugins/jszip/jszip.min.js"></script>
    <script src="/AdminLTE/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="/AdminLTE/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="/AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="/AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/AdminLTE/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="/AdminLTE/dist/js/demo.js"></script>
    <!-- Page specific script -->
    
</body>
</html>

proje1/proje1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bootshop online Shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--Less styles -->
    <!-- Other Less css file //different less files has different color scheam
     <link rel="stylesheet/less" type="text/css" href="/magaza/themes/less/simplex.less">
     <link rel="stylesheet/less" type="text/css" href="/magaza/themes/less/classified.less">
     <link rel="stylesheet/less" type="text/css" href="/magaza/themes/less/amelia.less">  MOVE DOWN TO activate
     -->
    <!--<link rel="stylesheet/less" type="text/css" href="/magaza/themes/less/bootshop.less">
    <script src="/magaza/themes/js/less.js" type="text/javascript"></script> -->
    <!-- Bootstrap style -->
    <link id="callCss" rel="stylesheet" href="/magaza/themes/bootshop/bootstrap.min.css" media="screen" />
    <link href="/magaza/themes/css/base.css" rel="stylesheet" media="screen" />
    <!-- Bootstrap style responsive -->
    <link href="/magaza/themes/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/magaza/themes/css/font-awesome.css" rel="stylesheet" type="text/css">
    <!-- Google-code-prettify -->
    <link href="/magaza/themes/js/google-code-prettify/prettify.css" rel="stylesheet" />
    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="/magaza/themes/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/magaza/themes/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/magaza/themes/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/magaza/themes/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/magaza/themes/images/ico/apple-touch-icon-57-precomposed.png">
    <style type="text/css" id="enject"></style>
</head>
<body>
    <div id="header">
        <div class="container">
            
            <!-- Navbar ================================================== -->
            <div id="logoArea" class="navbar">
                <a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-inner">
                    <a class="brand" href="/Home/Index">Anasayfa</a>


                    @Html.Partial("Arama")

                    @Html.Partial("_LoginPartial")



                </div>
            </div>
        </div>
    </div>
    <!-- Header End====================================================================== -->

    @RenderBody()


    <!-- Footer ================================================================== -->
  
    <!-- Placed at the end of the document so the pages load faster ============================================= -->
    <script src="/magaza/themes/js/jquery.js" type="text/javascript"></script>
    <script src="/magaza/themes/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/magaza/themes/js/google-code-prettify/prettify.js"></script>

    <script src="/magaza/themes/js/bootshop.js"></script>
    <script src="/magaza/themes/js/jquery.lightbox-0.5.js"></script>

    <!-- Themes switcher section ============================================================================================= -->
    <div id="secectionBox">
        <link rel="stylesheet" href="/magaza/themes/switch/themeswitch.css" type="text/css" media="screen" />
        <script src="/magaza/themes/switch/theamswitcher.js" type="text/javascript" charset="utf-8"></script>
        <div id="themeContainer">
            <div id="hideme" class="themeTitle">Style Selector</div>
            <div class="themeName">Oregional Skin</div>
            <div class="images style">
                <a href="/magaza/themes/css/#" name="bootshop"><img src="/magaza/themes/switch/images/clr/bootshop.png" alt="bootstrap business templates" class="active"></a>
                <a href="/magaza/themes/css/#" name="businessltd"><img src="/magaza/themes/switch/images/clr/businessltd.png" alt="bootstrap business templates" class="active"></a>
            </div>
            <div class="themeName">Bootswatch Skins (11)</div>
            <div class="images style">
                <a href="/magaza/themes/css/#" name="amelia" title="Amelia"><img src="/magaza/themes/switch/images/clr/amelia.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="spruce" title="Spruce"><img src="/magaza/themes/switch/images/clr/spruce.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="superhero" title="Superhero"><img src="/magaza/themes/switch/images/clr/superhero.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="cyborg"><img src="/magaza/themes/switch/images/clr/cyborg.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="cerulean"><img src="/magaza/themes/switch/images/clr/cerulean.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="journal"><img src="/magaza/themes/switch/images/clr/journal.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="readable"><img src="/magaza/themes/switch/images/clr/readable.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="simplex"><img src="/magaza/themes/switch/images/clr/simplex.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="slate"><img src="/magaza/themes/switch/images/clr/slate.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="spacelab"><img src="/magaza/themes/switch/images/clr/spacelab.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="united"><img src="/magaza/themes/switch/images/clr/united.png" alt="bootstrap business templates"></a>
                <p style="margin:0;line-height:normal;margin-left:-10px;display:none;"><small>These are just examples and you can build your own color scheme in the backend.</small></p>
            </div>
            <div class="themeName">Background Patterns </div>
            <div class="images patterns">
                <a href="/magaza/themes/css/#" name="pattern1"><img src="/magaza/themes/switch/images/pattern/pattern1.png" alt="bootstrap business templates" class="active"></a>
                <a href="/magaza/themes/css/#" name="pattern2"><img src="/magaza/themes/switch/images/pattern/pattern2.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern3"><img src="/magaza/themes/switch/images/pattern/pattern3.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern4"><img src="/magaza/themes/switch/images/pattern/pattern4.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern5"><img src="/magaza/themes/switch/images/pattern/pattern5.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern6"><img src="/magaza/themes/switch/images/pattern/pattern6.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern7"><img src="/magaza/themes/switch/images/pattern/pattern7.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern8"><img src="/magaza/themes/switch/images/pattern/pattern8.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern9"><img src="/magaza/themes/switch/images/pattern/pattern9.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern10"><img src="/magaza/themes/switch/images/pattern/pattern10.png" alt="bootstrap business templates"></a>

                <a href="/magaza/themes/css/#" name="pattern11"><img src="/magaza/themes/switch/images/pattern/pattern11.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern12"><img src="/magaza/themes/switch/images/pattern/pattern12.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern13"><img src="/magaza/themes/switch/images/pattern/pattern13.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern14"><img src="/magaza/themes/switch/images/pattern/pattern14.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern15"><img src="/magaza/themes/switch/images/pattern/pattern15.png" alt="bootstrap business templates"></a>

                <a href="/magaza/themes/css/#" name="pattern16"><img src="/magaza/themes/switch/images/pattern/pattern16.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern17"><img src="/magaza/themes/switch/images/pattern/pattern17.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern18"><img src="/magaza/themes/switch/images/pattern/pattern18.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern19"><img src="/magaza/themes/switch/images/pattern/pattern19.png" alt="bootstrap business templates"></a>
                <a href="/magaza/themes/css/#" name="pattern20"><img src="/magaza/themes/switch/images/pattern/pattern20.png" alt="bootstrap business templates"></a>

            </div>
        </div>
    </div>
    
</body>
</html>